In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.2.2'

In [3]:
filename = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv"

In [4]:
header = ["Laptop","Status","Brand","Model","CPU","RAM","Storage","Storage type","GPU","Screen","Touch","Final Price"]

In [5]:
df = pd.read_csv(filename, names = header)

In [6]:
df.head()

Laptop  Status   Brand  \
0                                             Laptop  Status   Brand   
1  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...     New    Asus   
2  Alurin Go Start Intel Celeron N4020/8GB/256GB ...     New  Alurin   
3  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...     New    Asus   
4  MSI Katana GF66 12UC-082XES Intel Core i7-1270...     New     MSI   

        Model            CPU  RAM  Storage  Storage type       GPU  Screen  \
0       Model            CPU  RAM  Storage  Storage type       GPU  Screen   
1  ExpertBook  Intel Core i5    8      512           SSD       NaN    15.6   
2          Go  Intel Celeron    8      256           SSD       NaN    15.6   
3  ExpertBook  Intel Core i3    8      256           SSD       NaN    15.6   
4      Katana  Intel Core i7   16     1000           SSD  RTX 3050    15.6   

   Touch         Final Price  
0  Touch         Final Price  
1     No  1008.9999999999999  
2     No               299.0  
3     No               789.0  
4     No              1199.0

In [7]:
#delete row 0
df2 = df.drop([0])

In [8]:
#How many records are in the dataset? 2160
df2.head()

Laptop Status   Brand  \
1  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
2  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
3  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
4  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
5  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU RAM Storage Storage type       GPU Screen Touch  \
1  ExpertBook  Intel Core i5   8     512          SSD       NaN   15.6    No   
2          Go  Intel Celeron   8     256          SSD       NaN   15.6    No   
3  ExpertBook  Intel Core i3   8     256          SSD       NaN   15.6    No   
4      Katana  Intel Core i7  16    1000          SSD  RTX 3050   15.6    No   
5         15S  Intel Core i5  16     512          SSD       NaN   15.6    No   

          Final Price  
1  1008.9999999999999  
2               299.0  
3               789.0  
4              1199.0  
5              669.01

In [9]:
df['Brand'].nunique()
df['Brand'].unique()

array(['Brand', 'Asus', 'Alurin', 'MSI', 'HP', 'Lenovo', 'Medion', 'Acer',
       'Apple', 'Razer', 'Gigabyte', 'Dell', 'LG', 'Samsung', 'PcCom',
       'Microsoft', 'Primux', 'Prixton', 'Dynabook Toshiba', 'Thomson',
       'Denver', 'Deep Gaming', 'Vant', 'Innjoo', 'Jetwing', 'Millenium',
       'Realme', 'Toshiba'], dtype=object)

In [10]:
#How many laptop brands are presented in the dataset 28

In [11]:
#How many columns in the dataset have missing values? 3
missing_data = df.isnull()

In [12]:
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")  

Laptop
Laptop
False    2161
Name: count, dtype: int64

Status
Status
False    2161
Name: count, dtype: int64

Brand
Brand
False    2161
Name: count, dtype: int64

Model
Model
False    2161
Name: count, dtype: int64

CPU
CPU
False    2161
Name: count, dtype: int64

RAM
RAM
False    2161
Name: count, dtype: int64

Storage
Storage
False    2161
Name: count, dtype: int64

Storage type
Storage type
False    2119
True       42
Name: count, dtype: int64

GPU
GPU
True     1371
False     790
Name: count, dtype: int64

Screen
Screen
False    2157
True        4
Name: count, dtype: int64

Touch
Touch
False    2161
Name: count, dtype: int64

Final Price
Final Price
False    2161
Name: count, dtype: int64



In [13]:
#What's the maximum final price of Dell notebooks in the dataset?
df2["Final Price"] = pd.to_numeric(df2["Final Price"])

In [14]:
df2[df2['Brand'] == 'Dell']['Final Price'].max()

3936.0

In [15]:
#Find the median value of Screen column in the dataset.
df2["Screen"] = pd.to_numeric(df2["Screen"])

In [16]:
df2['Screen'].median()

15.6

In [17]:
avg_screen = df2['Screen'].astype('float').mean()
print(avg_screen)

15.168112244897959


In [18]:
#Next, calculate the most frequent value of the same Screen column.
df2['Screen'].mode()

0    15.6
Name: Screen, dtype: float64

In [19]:
#Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
df2["Screen"].fillna(value='15.6')

1       15.6
2       15.6
3       15.6
4       15.6
5       15.6
        ... 
2156    17.3
2157    17.3
2158    17.3
2159    13.4
2160    13.4
Name: Screen, Length: 2160, dtype: object

In [20]:
df2['Screen'].median()
#    Now, calculate the median value of Screen once again.

#Has it changed? No

15.6

In [21]:
df2["Screen"] = pd.to_numeric(df2["Screen"])
df2["RAM"] = pd.to_numeric(df2["RAM"])
df2["Storage"] = pd.to_numeric(df2["Storage"])

In [22]:
#Q7. Sum of weights
df2[df2["Brand"]=="Innjoo"][["RAM","Storage","Screen"]].head(10)

RAM  Storage  Screen
1479    8      256    15.6
1480    8      512    15.6
1481    4       64    14.1
1482    6       64    14.1
1483    6      128    14.1
1484    6      128    14.1

In [23]:
#Get the underlying NumPy array. Let's call it X.
X= df2[df2["Brand"]=="Innjoo"][["RAM","Storage","Screen"]].to_numpy()
print(X)

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]


In [31]:
#Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = X.dot(X.T)
print(XTX)

[[ 65843.36 131379.36  16635.96  16651.96  33035.96  33035.96]
 [131379.36 262451.36  33019.96  33035.96  65803.96  65803.96]
 [ 16635.96  33019.96   4310.81   4318.81   8414.81   8414.81]
 [ 16651.96  33035.96   4318.81   4330.81   8426.81   8426.81]
 [ 33035.96  65803.96   8414.81   8426.81  16618.81  16618.81]
 [ 33035.96  65803.96   8414.81   8426.81  16618.81  16618.81]]


In [25]:
#Compute the inverse of XTX.
x = np.linalg.pinv(XTX)
print(x)

[[ 0.07685672 -0.03540126 -0.12193106  0.04199099  0.0139265   0.0139265 ]
 [-0.03540126  0.01651252  0.05568098 -0.01960876 -0.00663032 -0.00663032]
 [-0.12193106  0.05568098  0.19459549 -0.0659823  -0.02157929 -0.02157929]
 [ 0.04199099 -0.01960876 -0.0659823   0.02329208  0.00789214  0.00789214]
 [ 0.0139265  -0.00663032 -0.02157929  0.00789214  0.00275294  0.00275294]
 [ 0.0139265  -0.00663032 -0.02157929  0.00789214  0.00275294  0.00275294]]


In [26]:
y =np.array([1100, 1300, 800, 900, 1000, 1100])
print(y)

[1100 1300  800  900 1000 1100]


In [37]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w
z= x.dot(X.T)
print(z)

ValueError: shapes (6,6) and (3,6) not aligned: 6 (dim 1) != 3 (dim 0)

In [35]:
z.dot(y)

array([1180.71589467, 1290.24170249,  848.31155552,  939.47308762,
        966.85453958,  966.85453958])